#pragma once
const int WINDOW_WIDTH = 1280;
const int WINDOW_HEIGHT = 720;
const int DEFAULT_ARROW_HEIGHT = WINDOW_HEIGHT / 2;
const int ARROW_IMAGE_WIDTH = 60;
const int STRATAGEM_IMAGE_HEIGHT_LIMIT = 400;
const int STRATAGEM_IMAGE_WIDTH_LIMIT = 440;
const int STRATAGEM_AMOUNT_LIMIT = 6;