#pragma once

constexpr int MAX_BUFFER_SIZE = 250;
constexpr int WINDOW_WIDTH = 1280;
constexpr int WINDOW_HEIGHT = 720;
constexpr int DEFAULT_ARROW_HEIGHT = WINDOW_HEIGHT / 2;
constexpr int ARROW_IMAGE_WIDTH = 60;
constexpr int STRATAGEM_IMAGE_HEIGHT_LIMIT = 400;
constexpr int STRATAGEM_IMAGE_WIDTH_LIMIT = 440;
constexpr int STRATAGEM_AMOUNT_LIMIT = 6;
constexpr int POINTS_PER_STRATAGEM = 20;
constexpr int ROUND_POINTS = POINTS_PER_STRATAGEM * STRATAGEM_AMOUNT_LIMIT;